
# My TOML file for Pantheon instance for node1 domain

# Enable sidechains
sidechains-enabled=true

# Setup ERA access
finder-address="0xb417f71159ff9ffd583c840d4717d384d5977f16"
era-address="0xc9b2acd4ae7d82c8927ff7eed11bb723acdc0840"
infura-token="d9cf99544e124ffea85d3ba0b4f8aba2"

# Additional settings for this node
data-path="sidechains/node1"
network="dev"
discovery-enabled=true
rpc-http-enabled=true
rpc-http-port=30012
rpc-http-api=["SC"]
rpc-ws-enabled=true
rpc-ws-port=30013
rpc-ws-api=["SC"]
p2p-port=30011

# Setup for created sidechain nodes
sidechains-data-path="sidechains/sidechain"
sidechains-p2p-port=30014
sidechains-rpc-http-port=30015
sidechains-rpc-ws-port=30016
sidechains-sc-rpc-http-port=30017
