
# My TOML file for Pantheon instance for node1 domain

# Typical commandline to run Pantheon with this configuration file
# pantheon --config-file sidechains/dev_node1.toml

# Use "wscat -c ws://127.0.0.1:30012" to connect to the websocket in console mode
#     "{"jsonrpc":"2.0","method":"sidechains_create","params":["a.amazon.com.au"],"id":53}"

# Enable sidechains
sidechains-enabled=true

# Data location
data-path="sidechains/node1"

# Use development mode
network="dev"

# Enable JSON RPC interface
rpc-http-enabled=true
rpc-http-api=["ADMIN", "ETH", "NET"]
discovery-enabled=true
rpc-ws-enabled=true

# Setup port numbers
p2p-port=30011
rpc-http-port=30012
rpc-ws-port=30013

